# Generated by Django 3.2.5 on 2023-11-02 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default=None, max_length=255, upload_to='images/users/%Y/%m/%d'),
        ),
    ]
