# Generated by Django 3.2.5 on 2023-11-03 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='typ',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
    ]
