# Generated by Django 3.2.5 on 2023-11-03 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_profile_typ'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='typ',
            new_name='branch',
        ),
    ]
