# Generated by Django 3.2.5 on 2023-11-03 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_rename_typ_profile_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='branch',
        ),
    ]
