# Generated by Django 3.2.5 on 2023-11-03 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_remove_profile_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='typ',
            field=models.CharField(blank=True, default='Test', max_length=255),
        ),
    ]
