# Generated by Django 3.2.5 on 2023-11-03 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_profile_typ'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='typ',
        ),
    ]
