# Generated by Django 3.2.5 on 2023-11-03 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_remove_profile_typ'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='filiere',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
    ]
