# Generated by Django 3.2.5 on 2023-11-03 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_profile_filiere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='filiere',
            field=models.CharField(choices=[('Computer Science', 'Computer Science'), ('A2I', 'A2I'), ('Mechanical', 'Mechanical'), ('GI', 'GI')], default='Computer Science', max_length=20),
        ),
    ]
