# Generated by Django 3.2.5 on 2023-11-02 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('typ', models.CharField(default='Extra', max_length=200)),
                ('intervenant', models.CharField(default=None, max_length=200)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('file', models.FileField(max_length=200, upload_to='')),
            ],
        ),
    ]
