# Generated by Django 3.2.5 on 2023-11-02 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='time',
            field=models.CharField(choices=[('Automne', 'Automne'), ('Printemps', 'Printemps')], default='Automne', max_length=10),
        ),
    ]
