# Generated by Django 3.2.5 on 2023-11-02 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='typ',
            field=models.CharField(choices=[('Computer Science', 'Computer Science'), ('A2I', 'A2I'), ('Mechanical', 'Mechanical'), ('GI', 'GI')], max_length=20),
        ),
    ]
