# Generated by Django 3.2.5 on 2023-11-02 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_course_typ'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='typ',
            field=models.CharField(choices=[('Computer Science', 'Computer Science'), ('A2I', 'A2I'), ('Mechanical', 'Mechanical'), ('GI', 'GI')], default='Computer Science', max_length=20),
        ),
    ]
