# Generated by Django 3.2.5 on 2023-11-03 00:15

import course.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_course_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='file',
            field=models.FileField(max_length=200, upload_to=course.models.Course.get_file_upload_path),
        ),
    ]
