# Generated by Django 3.2.5 on 2023-11-03 01:32

import course.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_alter_course_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to=course.models.Course.get_image_upload_path),
        ),
    ]
